[workspace]
authors = ["MVPavan <mvpavan42@gmail.com>"]
channels = ["conda-forge"]
name = "mvpavan.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=25.2.1,<25.3"
python = ">=3.14.2,<3.15"
